from debian:testing

#run dpkg --add-architecture i386

run apt-get update
run apt-get upgrade -y

run apt-get install -y \
	bison build-essential curl flex git gnupg gperf \
	libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev \
	libwxgtk3.0-dev libxml2 libxml2-utils lzop maven \
	pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev \
	curl bc python python3 g++-multilib gcc-multilib lib32ncurses5-dev \
	lib32readline-dev lib32z1-dev gawk wget git-core diffstat vim \
	unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev \
	xterm locales ccache cpio imagemagick \
	gcc-6 \
	gcc-6-plugin-dev \
	openjdk-8-jdk \
	locales-all

run useradd -m tudor

run su -l tudor -s /bin/bash -c 'mkdir ~/bin && mkdir ~/share && \
	curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && \
	chmod a+x ~/bin/repo && \
	echo "export USER=$(whoami)" >> .bashrc && \
	echo "export USE_CCACHE=1" >> .bashrc && \
	echo "export PATH=/usr/lib/ccache:$PATH" >> .bashrc && \
	echo "export LC_ALL=en_US.UTF-8" >> .bashrc && \
	echo "export LANG=en_US.UTF-8" >> .bashrc && \
	echo "export LANGUAGE=en_US.UTF-8" >> .bashrc'

cmd su -l tudor -s /bin/bash
