from debian:stable

run dpkg --add-architecture i386
run apt-get update
run apt-get upgrade -y

run apt-get install -y \
	bison build-essential curl flex git gnupg gperf \
	libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev \
	libwxgtk3.0-dev libxml2 libxml2-utils lzop maven \
	pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev \
	curl bc python python3 g++-multilib gcc-multilib lib32ncurses5-dev \
	lib32readline-dev lib32z1-dev gawk wget git-core diffstat vim \
	unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev \
	xterm gcc-4.9 gcc-4.9-plugin-dev ccache \
	openjdk-8-jdk locales

run useradd -m tudor
run su -l tudor -s /bin/bash -c 'export USER=$(whoami)'
cmd su -l tudor -s /bin/bash
